// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sample_app.Models;

namespace sample_app.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20190321114739_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("sample_app.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ToDoListid");

                    b.Property<bool>("complete");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.HasIndex("ToDoListid");

                    b.ToTable("items");
                });

            modelBuilder.Entity("sample_app.Models.ToDoList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Userid");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("lists");
                });

            modelBuilder.Entity("sample_app.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("passwordHash");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("sample_app.Models.Item", b =>
                {
                    b.HasOne("sample_app.Models.ToDoList")
                        .WithMany("items")
                        .HasForeignKey("ToDoListid");
                });

            modelBuilder.Entity("sample_app.Models.ToDoList", b =>
                {
                    b.HasOne("sample_app.Models.User")
                        .WithMany("lists")
                        .HasForeignKey("Userid");
                });
#pragma warning restore 612, 618
        }
    }
}
