// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sample_app.Models;

namespace sample_app.Migrations
{
    [DbContext(typeof(ToDoContext))]
    partial class ToDoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("sample_app.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("complete");

                    b.Property<int>("listid");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.HasIndex("listid");

                    b.ToTable("items");
                });

            modelBuilder.Entity("sample_app.Models.ToDoList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("lists");
                });

            modelBuilder.Entity("sample_app.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("admin");

                    b.Property<string>("email");

                    b.Property<int>("passHashIterations");

                    b.Property<int>("passHashSize");

                    b.Property<int>("passSaltSize");

                    b.Property<string>("passwordHash");

                    b.Property<string>("passwordSalt");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("sample_app.Models.Item", b =>
                {
                    b.HasOne("sample_app.Models.ToDoList", "list")
                        .WithMany("items")
                        .HasForeignKey("listid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sample_app.Models.ToDoList", b =>
                {
                    b.HasOne("sample_app.Models.User", "user")
                        .WithMany("lists")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
